const mongoose = require('mongoose');

const MAX_MESSAGE_LENGTH = 1000;

const supportMessageSchema = new mongoose.Schema(
  {
    conversation: { type: mongoose.Schema.Types.ObjectId, ref: 'SupportConversation', required: true },
    sender: { type: String, enum: ['customer', 'admin'], required: true },
    senderUser: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    body: { type: String, required: true, trim: true, minlength: 1, maxlength: MAX_MESSAGE_LENGTH },
    // Generated by the sender's browser; lets a retried / double-submitted send be recognised as the same message
    clientId: { type: String, required: true },
    // null until the other side has opened the conversation
    readAt: { type: Date, default: null }
  },
  { timestamps: true }
);

supportMessageSchema.index({ conversation: 1, clientId: 1 }, { unique: true });
supportMessageSchema.index({ conversation: 1, _id: 1 });
supportMessageSchema.index({ sender: 1, readAt: 1 });

module.exports = mongoose.model('SupportMessage', supportMessageSchema);